name: docker

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GCHR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/x86_64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}"
